spring.application.name=sistema-entregas

# adicionando as configurações de conexão com o banco H2
# spring.datasource.url=jdbc:h2:mem:entregasdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.defer-datasource-initialization=true
# spring.h2.console.enable=true

# adiciona as configurações do postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/entregasdb
spring.datasource.username=postgres
spring.datasource.password=senha123
spring.jpa.hibernate.ddl-auto=update
spring.jp.defer-datasource-initialization=true